// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALiqtPotY_MbQQd57V4W2y6schjP8FReA',
    appId: '1:891075547608:web:9cd7f52acd3ab38bac62ad',
    messagingSenderId: '891075547608',
    projectId: 'billu-280604',
    authDomain: 'billu-280604.firebaseapp.com',
    storageBucket: 'billu-280604.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Yl83CDSGX9Z1zfIlLAhannQkQwi56b0',
    appId: '1:891075547608:android:f791cc3e0f5c9877ac62ad',
    messagingSenderId: '891075547608',
    projectId: 'billu-280604',
    storageBucket: 'billu-280604.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNeJjTJW8f0xGeaCUATll35G0JaHLosNg',
    appId: '1:891075547608:ios:5d20c9f9a068117fac62ad',
    messagingSenderId: '891075547608',
    projectId: 'billu-280604',
    storageBucket: 'billu-280604.firebasestorage.app',
    iosBundleId: 'com.practice.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNeJjTJW8f0xGeaCUATll35G0JaHLosNg',
    appId: '1:891075547608:ios:5d20c9f9a068117fac62ad',
    messagingSenderId: '891075547608',
    projectId: 'billu-280604',
    storageBucket: 'billu-280604.firebasestorage.app',
    iosBundleId: 'com.practice.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALiqtPotY_MbQQd57V4W2y6schjP8FReA',
    appId: '1:891075547608:web:92d0e5dafa7bb1adac62ad',
    messagingSenderId: '891075547608',
    projectId: 'billu-280604',
    authDomain: 'billu-280604.firebaseapp.com',
    storageBucket: 'billu-280604.firebasestorage.app',
  );
}
